[package]
name = "icarus-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.22", features = ["rt", "sync", "macros"] }
btleplug = "0.10"
anyhow = "1"
thiserror = "1"
uuid = "1"
byteorder = "1"
futures = "0.3"
pretty_env_logger = "0.4"
log = "0.4"
